### ISSUE TITLE
[M0-Dev] ¿Qué unidad usamos para representar la duración de un concierto?

### ISSUE THREAD

**Issue by danieeeld2** [josemponce/RutaMusical#11]
_Issue en relación a #9_

Generalmente, un concierto dura una determinada cantidad de horas y minutos o puede que solo minutos. Por convenio y facilidad creo que lo más óptimo es expresarlo todo en minutos.

**Comment by danieeeld2** [comment]
Si observamos el issue #14, vemos que se podría gestionar también con el paquete `"time"`, pero me parece más cómodo trabajarlo como un entero que refleja los minutos, para después poder trabajar con este dato de forma muy simple en el cálculo de la ganancia

**Comment by josemponce** [comment]
Perfecto :+1:
