### ISSUE TITLE
[M0-Dev] Para la lógica de negocio hace falta la disponibilidad de los músicos

### ISSUE THREAD

**Issue by danieeeld2** [josemponce/RutaMusical#12]
Si nos fijamos en #4 los músicos quieren descansar y no estar disponibles todos los días, por lo que sería conveniente no solo registrar los días que tienen disponibles para tocar, sino el número máximo de días que quieren tocar.

**Comment by JJ** [comment]
Asumir que estás hablando de la disponibilidad es asumir una solución para el problema. #4 dice que quieren "descansar un poco". Deberías plantear el problema de los descansos de los músicos, más que la disponibilidad (que sería algo que la lógica de negocio debería decidir)
