### ISSUE TITLE
[M0-Dev] ¿Qué tipo de dato usamos para las fechas y horas?

### ISSUE THREAD

**Issue by danieeeld2** [josemponce/RutaMusical#14]
_Issue en relación a #9  y #8"_

He estado investigando y en Go podemos utilizar el paquete `"time"` que nos permitirá manejar los datos de tipo fecha y hora con facilidad.

Para más documentación sobre como funciona este tipo, puedes consultar:
- https://gobyexample.com/time
- https://pkg.go.dev/time

**Comment by josemponce** [comment]
Perfecto :+1:
