### ISSUE TITLE
[M0-Dev] Decidir el lenguaje de programación

### ISSUE THREAD

**Issue by danieeeld2** [josemponce/RutaMusical#6]
Buenas, se me ha asignado este repositorio para el objetivo 2. Lo primero es elegir el lenguaje de programación, así que abro un nuevo issue.

### Preámbulo

El objetivo de este ticket es discutir y especificar el lenguaje de programación que se usará en el proyecto.

**Comment by danieeeld2** [comment]
¿Tienes alguna sugerencia? 
Yo había pensado que Go podría ser una buena idea, ya que cuenta con:

- Sintaxis simple.
- Excelente rendimiento y velocidad de ejecución.
- Importación simple de dependencias.

Los inconvenientes son que:

- No soporta datos genéricos.
- Oferta limitada de bibliotecas.

Espero tu opinión compañero y un placer colaborar contigo 😄

**Comment by josemponce** [comment]
Hola @danieeeld2 un placer también trabajar contigo.

Al igual que tú también me estuve planteando utilizar el lenguaje de Go, ya que a parte de las ventajas que mencionas encuentro algunas otras más:

 - Su similitud a lenguajes que ya conozco como C++.
 - Ser un lenguaje compilado puede ayudarme a depurar y encontrar errores más rápido.
 - Su gran repercusión en el mundo laboral lo convierte en un lenguaje muy interesante de conocer.

Espero tu opinión, un saludo :wave:.

**Comment by danieeeld2** [comment]
:+1:  Perfecto @josemponce. Si los dos estamos de acuerdo procedo  a crear la nueva rama y los primeros cambios para hacer el PR. Te aviso cuando este creado para poder asociarle el M0 al PR. 😄
