### ISSUE TITLE
[M0-Dev] ¿Qué estructuras necesitamos y cómo la organizamos en ficheros?

### ISSUE THREAD

**Issue by danieeeld2** [josemponce/RutaMusical#8]
_Issue referente a  #3 #4 #5_

Buenas @josemponce. Si nos fijamos en los issue, vemos que podemos extraer por una parte la `Agrupación Musical`, por otra los `Conciertos` y por último la `Ruta`.

### Agrupación Musical
- Esta entidad contará con la lista de los músicos y la disponibilidad de los mismos.

### Concierto
- Representa los conciertos y sus características más básicas: Fecha, lugar y dinero pagado.
_Aquí tengo algunas dudas que no reflejan las HUs pero que me surgen al leer el M1. ¿Quieres tener en cuenta la localización del pueblo, es decir, si está más o menos lejos y que eso influya en la ganancia?_

### Ruta
- Lista ordenada de los conciertos

Espero tus sugerencias y ya cuando aclaremos las ideas más básicas iré abriendo un issue para detallar cada parte e ir creando los ficheros😄

**Comment by josemponce** [comment]
Hola @danieeeld2 

Estoy de acuerdo con el modelo general que has presentado, aunque añadiría un par de cosas más para que luego resultara más fácil la elaboración del programa:

La primera sería la creación de la entidad `Músico`, donde se guarden los datos de los distintos miembros de cada agrupación musical como su nombre, DNI o el instrumento que tocan.

Por otro lado en la entidad `Concierto` estoy de acuerdo en añadir la localización del concierto porque como has indicado esto puede influir en la ganancia recibida de este.

Espero tu opinión sobre estos cambios, un saludo :wave:

**Comment by danieeeld2** [comment]
Okay, me parece bien😄. Por otro lado, al revisar el guión me he dado cuenta que debemos diferenciar entre entidades y objetos-valor (la principal característica de estos últimos es que suelen ser inmutables). Creo que los `Músicos` deberían ser objeto-valor, porque, en principio, no vamos a modificar sus valores y va a ser una "lista" permanente. Por otro lado, creo que para nuestro problema, los `Conciertos` deberían estar planteados de esta misma forma.

**Comment by danieeeld2** [comment]
Buenas de nuevo @josemponce he estado mirando un poco como gestionan los issues gente de otros años y leyendo bien el guión. Los issues deben estar planteados como problemas y deben aportar valor tanto al cliente como a las HUs, por lo que temas, como el que hemos hablado antes de las coordenadas, creo que deberían especificarse en nuevos issues. Así que voy a proceder a ir planteando algunas cosas

**Comment by josemponce** [comment]
Hola @danieeeld2.

Entiendo los cambios que propones y me parecen bien :+1:.

**Comment by JJ** [comment]
Esto no es en realidad el planteamiento de un problema; y apuntar a este issue en vez de hacerlo a la HU hace que uno se pierda un poco.

**Comment by JJ** [comment]
> Hola @danieeeld2
> 
> Estoy de acuerdo con el modelo general que has presentado, aunque añadiría un par de cosas más para que luego resultara más fácil la elaboración del programa:
> 
> La primera sería la creación de la entidad `Músico`, donde se guarden los datos de los distintos miembros de cada agrupación musical como su nombre, DNI o el instrumento que tocan.
> 
> Por otro lado en la entidad `Concierto` estoy de acuerdo en añadir la localización del concierto porque como has indicado esto puede influir en la ganancia recibida de este.
> 
> Espero tu opinión sobre estos cambios, un saludo 👋

No se puede comentar aquí la solución. Si hay información adicional, tiene que ir a la HU, en este caso #3 o #4
